workflows:
  target-app-build:
    name: Target App Build
    environment:
      flutter: 3.22.0
    scripts:
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release --verbose
    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
